version: '3'
services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./mysql/data:/var/lib/mysql
  web:
    build: .
    command: /bin/sh -c "rm -f tmp/pids/server.pid && mkdir -p mysql/data && rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - db
    ports:
      - "80:3000"
    volumes:
      - .:/app_name
