version: '3'
services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./mysql/data:/var/lib/mysql
  web:
    build: .
    command: >
      /bin/sh -c "rm -f tmp/pids/server.pid &&
      mkdir -p mysql/data &&
      RAILS_ENV=production bundle exec rails assets:precompile &&
      RAILS_ENV=production bundle exec puma -C config/puma.rb"
    depends_on:
      - db
    volumes:
      - .:/app_name
    environment:
      RAILS_ENV: production
  nginx:
    build:
      context: ./nginx
    volumes:
      - ./public:/app_name/public
      - ./tmp:/app_name/tmp
    ports:
      - "80:80"
    depends_on:
      - web
