User.create(name: 'admin', email: 'admin@test.com', password: 'password')
User.create(name: 'satou', email: 'satou@test.com', password: 'password')
User.create(name: 'suzuki', email: 'suzuki@test.com', password: 'password')
User.create(name: 'tanaka', email: 'tanaka@test.com', password: 'password')
User.create(name: 'test',email: 'test@test.com', password: 'password')

User.first.items.create(title: 'Sample1', status: 0, price: 1000, lecture: "心のオシャレ学", teacher: "田中太郎", memo: "表紙に若干のイタミあり。")
User.first.items.create(title: 'Sample2', status: 1, price: 1500, lecture: "心のオシャレ学", teacher: "田中太郎", memo: "表紙に若干のイタミあり。")
User.first.items.create(title: 'Sample3', status: 2, price: 500, lecture: "心のオシャレ学", teacher: "田中太郎", memo: "表紙に若干のイタミあり。")
User.second.items.create(title: 'Sample4', status: 0, price: 1000, lecture: "論理学", teacher: "小泉進次郎", memo: "全体的に良好な状態です。")
User.second.items.create(title: 'Sample5', status: 1, price: 1500, lecture: "論理学", teacher: "小泉進次郎", memo: "全体的に良好な状態です。")
User.second.items.create(title: 'Sample6', status: 2, price: 500, lecture: "論理学", teacher: "小泉進次郎", memo: "全体的に良好な状態です。")
